source("./R/libraries.R") # load the libraries

tar_source(files = c(
  "R/libraries.R",
  "R/functions.R"
)) # get the functions from the ./R/functions.R file

# controller for parallel computing
my_controller <- crew_controller_local(
  name = "my_pc_local",
  workers = 6,
  options_local = crew_options_local(log_directory = "./logs/crew/")
)

# metrics (CPU and RAM used by the different process, can be used to check if RAM is not enough)
if (tar_active()) {
  my_controller$start()
  log_start(
    path = "./logs/autometric.txt",
    seconds = 3,
    pids = my_controller$pids()
  )
}

tar_option_set(
  tidy_eval = T,
  seed = 5114,
  controller = my_controller, # parallel processing if the targets need it
  format = "qs", # efficient save format
  memory = "transient", # unload the targets after the steps are completed
  packages = c(
    "readr", "openxlsx",
    "quarto", # needed to render the pipeline as the last step
    "tidyverse", "magrittr", "here", "utils", "stringr",
    "longmixr", "FFTrees", "ashr",
    "conflicted"
  )
)

list(
  # save seed value that will be used by the functions in the pipeline if needed
  tar_target(seed, 5114,
    description = "seed used for the longmixr algorithm"
  ),
  tar_target(permut, 10,
    description = "number of permutation of the longmixr algorithm (set to 10 to not rerun the entire 1000 permutations as it can take an entire day)"
  ),
  tar_target(max_cluster, 2), # must be a positive integer (between 1 and 5)
  # get the name as the data file as a string
  # format = "file" is here to indicate to the pipeline to check the file it point for changes
  tar_target(psycourse_non_imputed,
    "./data/PsyCourse/220623_PsyCourse5.0_Pheno_Poschmann_multil_intgr_omics_NONIMPUTED.RData",
    format = "file",
    description = "Variable measured during the psycourse study (no imputation)"
  ),
  tar_target(psycourse_imputed,
    "./data/PsyCourse/220112_PsyCourse5.0_Pheno_Poschmann_multil_intgr_omics_IMPUTED.RData",
    format = "file",
    description = "Variable with missing values for some participants (imputation was realized by the IPPG)"
  ),
  tar_target(psycourse_center,
    "./data/PsyCourse/220907_PsyCourse5.0_CENTER_VARIABLES_Poschmann_multil_intgr_omics_NONIMPUTED.RData",
    format = "file",
    description = "Indicate the centers in which the participants were recruited"
  ),
  tar_target(psycourse_bmi,
    "./data/PsyCourse/240522_PsyCourse6.0_Pheno_Proposal_48add_bmi.RData",
    format = "file",
    description = "BMI of the participants (contains missing values)"
  ),
  tar_target(psycourse_additionnal,
    "./data/PsyCourse/250513_PsyCourse6.0_Pheno_Proposal_048_additional_data.RData",
    format = "file",
    description = "Additional data of physical measures and somatic disease of the PsyCourse participants"
  ),
  # Different operating systems may give different clustering even with the same R and packages version.
  # This seem to be caused by the way they handle the seed used by longmixr
  tar_target(publication_clusters,
    "./data/PsyCourse/longmixr/data.RData",
    format = "file",
    description = "RData file with the clustering we presented in our publication."
  ),
  # PRS of the PsyCourse participants (for those who were genotyped only)
  # Those files were generated by the IPPG of Munich
  tar_target(psycourse_prs_md,
    "./data/PsyCourse/PRS/PsyCourse_MimicSS_mdd2018_PRScs_scores.txt",
    format = "file",
    description = "PRS for MD of the participants"
  ),
  tar_target(psycourse_prs_bd,
    "./data/PsyCourse/PRS/PsyCourse_MimicSS_bip3_PRScs_scores.txt",
    format = "file",
    description = "PRS for BD of the participants"
  ),
  tar_target(psycourse_prs_scz,
    "./data/PsyCourse/PRS/PsyCourse_MimicSS_scz3_PRScs_scores.txt",
    format = "file",
    description = "PRS for SCZ of the participants"
  ),
  tar_target(psycourse_prs_treatment,
    "./data/PsyCourse/PRS/PsyCourseTreatmentPRS.profile",
    format = "file",
    description = "PRS for antipsychotic treatment of the participants"
  ),
  tar_target(psycourse_prs_pfactor,
    "./data/PsyCourse/PRS/PsyCoursePFactorPRS.profile",
    format = "file",
    description = "PRS for the P factor of the participants"
  ),
  tar_target(
    psycourse_clinical,
    GetAndFormatClinicalData(psycourse_non_imputed, psycourse_imputed)
  ),
  tar_target(
    psycourse_dimensions,
    GetClassificationDimensions(psycourse_clinical)
  ),

  # to reduce the computation time we only do the computation on the combination with all 5 variables groups (what is presented in the article). Originally we did it with all possible combinations.
  # by indicating a value lower than 4 (0 to 3), we can also do the computation for the other combinations
  tar_target(dimensions_combinations, psycourse_dimensions$VarComb[str_count(psycourse_dimensions$VarComb, "_") >= 4]),
  tar_target(
    corrected_dimensions,
    DimensionsCorrection(psycourse_dimensions)
  ),
  tar_target(clusters,
    LongmixrClustering(corrected_dimensions, dimensions_combinations, seed, permut, max_cluster),
    pattern = map(dimensions_combinations)
  ),
  tar_target(clusters_assignments, GetClusterAssignments(
    clusters,
    psycourse_clinical,
    psycourse_imputed,
    psycourse_non_imputed,
    psycourse_center,
    psycourse_prs_md,
    psycourse_prs_bd,
    psycourse_prs_scz,
    psycourse_prs_treatment,
    psycourse_prs_pfactor,
    psycourse_bmi
  )),
  # The clustering presented in our publication was originaly computed on the bird cluster (linux) while this quarto project was compiled on windows.
  # We observed differences (5 participants) when redoing the clustering on another operating system (windows) with the same R and packages versions.
  # We also observed this level of difference using different seed and also different number of max_k in the longmixr function.
  # This is probably due to the way the different operating system handle the seed.
  # The next step of the pipeline add a PANSS_YMRS_IDSC_COGNITION_FUNCTIONNING column, corresponding to the clustering solution in our publication.
  # This will allow us to make sure the clustering used next is the same no matter which operating system is used to run this pipeline
  tar_target(cluster_assignments2,
    ForcePublicationClusters(clusters_assignments, publication_clusters),
    description = "dataframe with participants phenotypes and clusters. A column with the original clustering (computed on BiRD cluster) to make sure he was always used."
  ),
  tar_target(olink_npx_file,
    "./data/MulioBio/OLINK/O-MulioBio-PsyCourse_NPX_2023-10-05.csv",
    format = "file"
  ),
  tar_target(
    olink_npx,
    ProtReadNPX(olink_npx_file, cluster_assignments2, psycourse_non_imputed)
  ),
  tar_target(qvalue_threshold, command = c(0.01, 0.05, 0.1, 0.2)),
  tar_target(olink_limma, OlinkLimma(olink_npx)),
  tar_target(olink_go_fit, ComputeOlinkGO(olink_limma, qvalue_threshold),
    pattern = qvalue_threshold
  ),
  tar_target(olink_go_fit_2, CorrectGOList(olink_go_fit)),
  tar_target(olink_cor, ComputeOlinkCor(olink_npx, olink_limma, cluster_assignments2)),
  tar_target(olink_cor_treatment, ComputeOlinkCorTreatment(olink_npx, olink_limma, cluster_assignments2))
)
